language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

install:
  - pip install -r requirements.txt
  - pip install python-coveralls

script:
  - py.test --cov=json_reindent tests/

after_success:
  coveralls
